// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"service/internal/interfaces"
)

type FouServicePrintString func(ctx context.Context, id string) (err error)
type FouServiceGet func(ctx context.Context, id string) (answ string, err error)

type MiddlewareFouService func(next interfaces.FouService) interfaces.FouService

type MiddlewareFouServicePrintString func(next FouServicePrintString) FouServicePrintString
type MiddlewareFouServiceGet func(next FouServiceGet) FouServiceGet
