// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

type requestFouServicePrintString struct {
	Id string `json:"id"`
}

// Formal exchange type, please do not delete.
type responseFouServicePrintString struct{}

type requestFouServiceGet struct {
	Id string `json:"id"`
}

type responseFouServiceGet struct {
	Answ string `json:"answ"`
}
