openapi: 3.0.0
servers:
    - {}
paths:
    /v1/get/:id:
        get:
            tags:
                - FouService
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/responseFouServiceGet'
    /v1/printstring/:id:
        post:
            tags:
                - FouService
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: Successful operation
components:
    schemas:
        requestFouServiceGet:
            type: object
        requestFouServicePrintString:
            type: object
        responseFouServiceGet:
            type: object
            properties:
                answ:
                    type: string
        responseFouServicePrintString:
            type: object
